config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    mount ActionCable.server => '/cable'
  end  

  root controller: :chat, action: :index
  devise_for :users
  resources :chat, only: [:index, :show, :create]
  resources :message, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :chats
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    if user_signed_in?
      @chats = current_user.chats
      @users = get_users(get_existing_chat_users)
    end
  end

  def show
    @chat = Chat.find(params[:id])
    @messages = Message.where(chat_id: params[:id])
    @chat_partner = @chat.users.select { |user| user != current_user }.first
  end

  def create
    user = User.find_by_id(params[:user])
    chat = Chat.create()
    chat.users << [current_user, user]
    redirect_to chat_path(chat)
  end

  private

  def get_existing_chat_users
    @chats.map{ |chat| chat.users.select{ |user| user }}.flatten
  end

  def get_users(existing_chat_users)
    User.all.select{ |user| !existing_chat_users.include?(user) }
  end
  
end

app/controllers/message_controller.rb
# frozen_string_literal: true

class MessageController < ApplicationController
  before_action :authenticate_user!
  def create
    message = current_user.messages.new(message_params)
    chat = Chat.find_by_id(message_params[:chat_id])
    if message.save
      ActionCable.server.broadcast("chat_channel_#{chat.id}", message: message.text, from: current_user.email)
      head :ok
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :chat_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/views/chat/index.html.haml
-if user_signed_in?
  .main
    .chats
      %h4 Active chats:
      -@chats.each do |chat|
        -chat.users.each do |user|
          -unless user === current_user
            %p=link_to "Chat with #{user.email}", chat_path(chat.id), { class: 'links join'}
    .chats
      %h4 Start a new chat with:
      -@users.each do |user|
        -unless user == current_user
          =link_to "#{user.email}", chat_index_path(user: user), { class: 'links join' , method: :post }
          %br/

app/views/chat/show.html.haml
.main
  .chats
    ="Chat with: #{@chat_partner.email}"
    -@messages.each do |message|
      -if message.user.email == current_user.email
        %p.send-message= message.text
      - else
        %p.receive-message= message.text
    #message_window.message-container
    = form_with scope: :message, url: message_index_path, id: :chat_form do | form |
      = form.hidden_field :chat_id, value: @chat.id, id: :chat_id
      = form.hidden_field :current_user_email, value: current_user.email, id: :current_user_email

      %p
        = form.label 'Send Message'
        %br/
        = form.text_field :text
      %p
        = form.submit "Send"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'partials/navbar'
    = yield

app/views/partials/_navbar.html.haml
.navbar
  =link_to 'Home', root_path, {class: 'links'}
  -unless user_signed_in?
    =link_to 'Register', new_user_registration_path , {class: 'links'}
    =link_to 'Login', new_user_session_path, {class: 'links'}
  - else
    %span.links=link_to 'Logout', destroy_user_session_path, {class: 'links', method: :delete }
    %span=current_user.email